services:
  - type: web
    name: tripcraft-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false